/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as ErkundenRouteImport } from './routes/erkunden'
import { Route as EntdeckenRouteImport } from './routes/entdecken'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicIdRouteImport } from './routes/topic.$id'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiFollowupRouteImport } from './routes/api/followup'
import { Route as ApiAskRouteImport } from './routes/api/ask'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ErkundenRoute = ErkundenRouteImport.update({
  id: '/erkunden',
  path: '/erkunden',
  getParentRoute: () => rootRouteImport,
} as any)
const EntdeckenRoute = EntdeckenRouteImport.update({
  id: '/entdecken',
  path: '/entdecken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdRoute = TopicIdRouteImport.update({
  id: '/topic/$id',
  path: '/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowupRoute = ApiFollowupRouteImport.update({
  id: '/api/followup',
  path: '/api/followup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entdecken': typeof EntdeckenRoute
  '/erkunden': typeof ErkundenRoute
  '/passport': typeof PassportRoute
  '/welcome': typeof WelcomeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/followup': typeof ApiFollowupRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entdecken': typeof EntdeckenRoute
  '/erkunden': typeof ErkundenRoute
  '/passport': typeof PassportRoute
  '/welcome': typeof WelcomeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/followup': typeof ApiFollowupRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entdecken': typeof EntdeckenRoute
  '/erkunden': typeof ErkundenRoute
  '/passport': typeof PassportRoute
  '/welcome': typeof WelcomeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/followup': typeof ApiFollowupRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/entdecken'
    | '/erkunden'
    | '/passport'
    | '/welcome'
    | '/api/ask'
    | '/api/followup'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/youtube'
    | '/topic/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entdecken'
    | '/erkunden'
    | '/passport'
    | '/welcome'
    | '/api/ask'
    | '/api/followup'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/youtube'
    | '/topic/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/entdecken'
    | '/erkunden'
    | '/passport'
    | '/welcome'
    | '/api/ask'
    | '/api/followup'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/youtube'
    | '/topic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EntdeckenRoute: typeof EntdeckenRoute
  ErkundenRoute: typeof ErkundenRoute
  PassportRoute: typeof PassportRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiFollowupRoute: typeof ApiFollowupRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
  TopicIdRoute: typeof TopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erkunden': {
      id: '/erkunden'
      path: '/erkunden'
      fullPath: '/erkunden'
      preLoaderRoute: typeof ErkundenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entdecken': {
      id: '/entdecken'
      path: '/entdecken'
      fullPath: '/entdecken'
      preLoaderRoute: typeof EntdeckenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id': {
      id: '/topic/$id'
      path: '/topic/$id'
      fullPath: '/topic/$id'
      preLoaderRoute: typeof TopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/followup': {
      id: '/api/followup'
      path: '/api/followup'
      fullPath: '/api/followup'
      preLoaderRoute: typeof ApiFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EntdeckenRoute: EntdeckenRoute,
  ErkundenRoute: ErkundenRoute,
  PassportRoute: PassportRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAskRoute: ApiAskRoute,
  ApiFollowupRoute: ApiFollowupRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
  TopicIdRoute: TopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
