// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type LumiPublicConfig = {
  supabaseUrl?: string;
  supabasePublishableKey?: string;
};

declare global {
  interface Window {
    __LUMI_PUBLIC_CONFIG__?: LumiPublicConfig;
  }
}

// Lumi uses the existing Saathi Supabase project. These are public client credentials,
// not privileged secrets. Keeping a built-in fallback avoids Vercel build-time env
// quirks while service-role/secret keys remain server-only.
const DEFAULT_SUPABASE_URL = 'https://xvlflsdanfzytxlwpthr.supabase.co';
const DEFAULT_PUBLISHABLE_KEY_B64 = 'c2JfcHVibGlzaGFibGVfTE8xa2lWd3Z4NVBacGdWeFJHX3M3QV9BMlk0aG5zNg==';
const LUMI_AUTH_REDIRECT = 'https://lumi-five-beryl.vercel.app/welcome';

function decodePublishableKey(): string {
  if (typeof atob === 'function') return atob(DEFAULT_PUBLISHABLE_KEY_B64);
  if (typeof Buffer !== 'undefined') return Buffer.from(DEFAULT_PUBLISHABLE_KEY_B64, 'base64').toString('utf-8');
  return '';
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const viteEnv = import.meta.env as Record<string, string | undefined>;
  const processEnv = typeof process !== 'undefined' ? process.env : undefined;
  const runtimeConfig = typeof window !== 'undefined' ? window.__LUMI_PUBLIC_CONFIG__ : undefined;

  const SUPABASE_URL =
    runtimeConfig?.supabaseUrl ||
    viteEnv.VITE_SUPABASE_URL ||
    processEnv?.SUPABASE_URL ||
    DEFAULT_SUPABASE_URL;

  const SUPABASE_PUBLISHABLE_KEY =
    runtimeConfig?.supabasePublishableKey ||
    viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    viteEnv.VITE_SUPABASE_ANON_KEY ||
    viteEnv.VITE_SUPABASE_KEY ||
    processEnv?.SUPABASE_PUBLISHABLE_KEY ||
    processEnv?.SUPABASE_ANON_KEY ||
    processEnv?.SUPABASE_KEY ||
    decodePublishableKey();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Lumi Supabase client configuration is unavailable.');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _authProxy: ReturnType<typeof createSupabaseClient>['auth'] | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();

    if (prop === 'auth') {
      if (!_authProxy) {
        const auth = _supabase.auth;
        _authProxy = new Proxy(auth, {
          get(target, authProp, authReceiver) {
            if (authProp === 'signInWithOAuth') {
              return (credentials: any) =>
                target.signInWithOAuth({
                  ...credentials,
                  options: {
                    ...(credentials?.options ?? {}),
                    redirectTo: LUMI_AUTH_REDIRECT,
                  },
                });
            }

            const value = Reflect.get(target, authProp, authReceiver);
            return typeof value === 'function' ? value.bind(target) : value;
          },
        });
      }
      return _authProxy;
    }

    return Reflect.get(_supabase, prop, receiver);
  },
});
